#!/usr/bin/env node

/*
 * Copyright 2014-2015 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

var fs = require('fs');
var lambda = require('./index');

if (process.argv.length !== 3) {
	console.log("You must provide the configuration file as an argument");
	process.exit(-1);
}

if (process.env['AWS_REGION'] === undefined) {
	console.log("No AWS Region set. Using default us-east-1");
}

// load the required configuration
var contentBuffer = fs.readFileSync(process.argv[2]);
var event = JSON.parse(contentBuffer);

function context() {}
context.done = function(status, message) {
	console.log("Context Closure Status: " + JSON.stringify(status) + "\n" + JSON.stringify(message));

	if (status && status !== null) {
		process.exit(-1);
	} else {
		process.exit(0);
	}
};

lambda.handler(event, context);
