
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "cd4e1e96184f61cefa7ecb00b2fc88062aa65e5f",
 "version": "1.10.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
